### ISSUE TITLE
port chart-vault to gitlab

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/chart-vault#50]
- [x]  Follow [instructions](https://github.com/samsung-cnct/solas/blob/master/docs/gitlab.md) to create  and edit`/.gitlab-ci.yml` from [template](https://github.com/samsung-cnct/solas-chart/blob/master/.gitlab-ci.yml)
- [x] also create `build/build.sh` and `build/test.sh` according to instructions
- [x] make build.sh and test.sh executable
- [x] create secret variable in gitlab
- [x] add pipeline status badge to README
- [x] Remove the `Jenkinsfile` in the current repo.
- [ ] When PR has merged, make sure that new image is being created on quay. Afterwards,  please head back to the [umbrella ticket](https://github.com/samsung-cnct/issues/issues/89) and check off the `chart-vault`

**Comment by leahnp** [comment]
Waiting on @notjames to review and merge #89

**Comment by leahnp** [comment]
Work done here: https://github.com/samsung-cnct/chart-vault/commit/94fb0001757539baa44e2972a7e64b01b68dea95
